### ISSUE TITLE
Says cannot open audio device : no such file or directory

### ISSUE THREAD

**Issue by sriranjanr** [zonque/simple-alsa-loop#1]
Hello,

I have attached 3 USB audio cards and I still get error message. Could you tell me how to fix this. 
Typing "aplay -l" gives this:
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
***\* List of PLAYBACK Hardware Devices ****
card 0: PCH [HDA Intel PCH], device 0: ALC283 Analog [ALC283 Analog]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: PCH [HDA Intel PCH], device 3: HDMI 0 [HDMI 0]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: Device [USB PnP Sound Device], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 2: Device_1 [USB PnP Sound Device], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 3: Device_2 [USB PnP Sound Device], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

**Comment by zonque** [comment]
You need to tweak the device strings, which are currently hard-coded. I'm sure "hw:0,1" is non-existent on your system, so just set it to something that matches your config.

This is not an end-user tool but rather a developer's debugging thing.

**Comment by sriranjanr** [comment]
Could you please tell me with the current output from aplay -l how shall I set the device. I changed the hardcoded thing to hw:0,0 which showed error with sample format and it does not identify hw:0,1

**Comment by zonque** [comment]
If you get a sample format error, you need to adopt these hard-coded settings as well. The tool uses `hw:`, which means no ALSA format adaption plugin will jump in and translate things for you, so you need to use a native supported format.

Again, this is not an end-user tool. I strongly believe if these things are not obvious to you, it's not a tool that will be of much use to you, sorry.

**Comment by sriranjanr** [comment]
I am ok with this source file.I will modify and manage it but I am new to alsa.If you can guide me then it will be very helpful and I will be thankful to you.
